"""add document_blocks seq + section_path (E10 TOC)

Revision ID: 991c8ae37ffc
Revises: 0358ed063ee1
Create Date: 2026-06-05 16:25:13.251111
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '991c8ae37ffc'
down_revision: Union[str, None] = '0358ed063ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_blocks', sa.Column('seq', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_blocks', sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_blocks', 'section_path')
    op.drop_column('document_blocks', 'seq')
    # ### end Alembic commands ###
