"""acl_entries: typed principals (user|role)

Revision ID: e3f1c2b8a4d7
Revises: f9a4d8c1e527
Create Date: 2026-06-10 00:00:00.000000

A1 fix: the original ``acl_entries.principal_id`` was a UUID FK to ``users.id``, which means
the only writer (the upload path) could grant read to one specific user — never to a role.
Non-admin users could therefore never see documents uploaded by admin (or anyone else),
which manifested as the pipeline warning "no authorized documents matched the query" on
every chat request from a non-admin caller.

This migration makes ``principal_id`` a string and adds ``principal_type ∈ {user, role}``.
Existing rows backfill to ``principal_type='user'`` with the UUID cast to text. The FK to
``users`` is dropped (role principals like ``'user'`` aren't rows in ``users``).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3f1c2b8a4d7'
down_revision: Union[str, None] = 'f9a4d8c1e527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the old composite unique + FK. Names were autogenerated by the initial migration,
    # and the unique's truncated suffix varies by Postgres version, so look them up by table
    # rather than hardcoding. IF EXISTS keeps a partially-applied re-run from breaking.
    bind = op.get_bind()
    old_unique = bind.execute(
        sa.text(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid = 'acl_entries'::regclass AND contype = 'u'"
        )
    ).scalar()
    if old_unique:
        op.execute(f'ALTER TABLE acl_entries DROP CONSTRAINT "{old_unique}"')
    op.execute(
        'ALTER TABLE acl_entries DROP CONSTRAINT IF EXISTS acl_entries_principal_id_fkey'
    )

    op.add_column(
        'acl_entries',
        sa.Column(
            'principal_type',
            sa.String(length=16),
            nullable=False,
            server_default='user',
        ),
    )
    # Retype principal_id from UUID to text, casting existing values.
    op.alter_column(
        'acl_entries',
        'principal_id',
        type_=sa.String(length=64),
        postgresql_using='principal_id::text',
        existing_nullable=False,
    )
    op.create_unique_constraint(
        'uq_acl_entries_resource_principal_permission',
        'acl_entries',
        ['resource_id', 'resource_type', 'principal_type', 'principal_id', 'permission'],
    )


def downgrade() -> None:
    op.drop_constraint(
        'uq_acl_entries_resource_principal_permission',
        'acl_entries',
        type_='unique',
    )
    # Best-effort reverse: cast back to UUID. Rows whose principal_id isn't a valid UUID
    # (i.e. role principals like 'user') will fail the cast — by design, since the old
    # schema can't represent them. Drop those rows first.
    op.execute(
        "DELETE FROM acl_entries WHERE principal_type <> 'user' "
        "OR principal_id !~ '^[0-9a-fA-F-]{36}$'"
    )
    op.alter_column(
        'acl_entries',
        'principal_id',
        type_=sa.dialects.postgresql.UUID(),
        postgresql_using='principal_id::uuid',
        existing_nullable=False,
    )
    op.drop_column('acl_entries', 'principal_type')
    op.create_foreign_key(
        'acl_entries_principal_id_fkey',
        'acl_entries',
        'users',
        ['principal_id'],
        ['id'],
    )
    op.create_unique_constraint(
        'acl_entries_resource_id_resource_type_principal_id_permis_key',
        'acl_entries',
        ['resource_id', 'resource_type', 'principal_id', 'permission'],
    )
